spring:
    application:
        name: Server
    datasource:
        url: jdbc:postgresql://${weblabedb.postgres.host}:${weblabedb.postgres.port}/${weblabedb.postgres.db}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        username: ${weblabedb.postgres.username}
        password: ${weblabedb.postgres.password}
        driver-class-name: org.postgresql.Driver
    jackson:
      property-naming-strategy: SNAKE_CASE
server:
    port: 8080

weblabedb:
    postgres:
        host: 124.221.95.132
        port: 5432
        db: webappdb
        username: webuser
        password: web_experiment

mybatis-plus:
    configuration:
        # 映射驼峰（实体属性名）到下划线（列名）
        map-underscore-to-camel-case: true
    mapper-locations: classpath:mapper/*.xml
    type-aliases-package: com.weblab.server.entity

alioss:
  endpoint: oss-cn-shanghai.aliyuncs.com
  access-key-id: LTAI5tAN9c1RzEn9tCh4amtj
  access-key-secret: ovLOyOeYpEYJXzqjFdJZJpJyhz9x6e
  bucket-name: testbucket-3100157652

